### ISSUE TITLE
No verification on uploaded file extension (Team 3)

### ISSUE THREAD

**Issue by norantharowat** [ELG7186-s22/project-group-4#43]
You do not verify the extension of the uploaded file in the ( /editConfig/upload ) route, which allows users to upload files with unsupported extensions.

you should limit the user to only upload the extension you want. 

You only change the file name to what you want, without taking the internal data of the file into consideration.

![image](https://user-images.githubusercontent.com/43759597/182615370-7815e4a6-3261-4997-88c5-0b430255b960.png)

**Comment by MagicianMido32** [comment]
Only the admin can access such file, the uploading of shell is prevented by renaming the file.
to better utilize resources, a business decision was made to follow a minimalist approach and base the whole security of the site on the safety and trust of the admin account. all resources were devoted to securing access to the admin account and prevent normal users from escalating their privileges. this is a wiser decision because we minimized the attack surface and delivered the required feature adhering to the available resources.
overcomplicating your code lead to many logic bugs that are hard to fix (need multiple guard clauses... cat and mouse game)
