### ISSUE TITLE
Violating the least functionality principle (Team 3) 

### ISSUE THREAD

**Issue by norantharowat** [ELG7186-s22/project-group-4#46]
Your flow includes downloading a config file for the admin to edit, and upload the edited config file to control the show and hide solutions button. 

The config file that you allow the admin to download, contains a lot of sensitive data that the admin does not need to know, above of that the admin is allowed to change other un related configurations, like the location where the local users are saved.

It is better to just allow the user to update the disabled solutions field using a normal form with an input combo box to pick certain challenges, hence you will have more control on the user's input and protect your configurations structure.
 
![image](https://user-images.githubusercontent.com/43759597/182792782-df5b02b1-8d96-46c8-a1bc-0aef416611bb.png)

**Comment by MagicianMido32** [comment]
Only the admin can access such file, the uploading of shell is prevented by renaming the file.
to better utilize resources, a business decision was made to follow a minimalist approach and base the whole security of the site on the safety and trust of the admin account. all resources were devoted to securing access to the admin account and prevent normal users from escalating their privileges. this is a wiser decision because we minimized the attack surface and delivered the required feature adhering to the available resources.
overcomplicating your code lead to many logic bugs that are hard to fix (need multiple guard clauses... cat and mouse game)
